"""create schema

Revision ID: 5e96a39d5776
Revises: 
Create Date: 2026-03-20 17:03:15.838118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e96a39d5776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def verify_rls(tables: list[str]) -> None:
    """Verify RLS is enabled on all specified tables. Call at end of upgrade()."""
    for table in tables:
        op.execute(
            f"DO $$ BEGIN "
            f"IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname='{table}' AND relrowsecurity) "
            f"THEN RAISE EXCEPTION 'RLS not enabled on table: {table}'; "
            f"END IF; END $$;"
        )


def upgrade() -> None:
    """Upgrade schema."""
    # REMINDER: Enable RLS on new tenant-scoped tables:
    # op.execute("ALTER TABLE tablename ENABLE ROW LEVEL SECURITY")
    # verify_rls(["tablename"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_cache',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('query_hash', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'query_hash', name='uq_enrichment_tenant_hash')
    )
    op.create_index('idx_enrichment_cache_ttl', 'enrichment_cache', ['created_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trial_expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now() + interval '90 days'"), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('context_catalog',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='empty', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'file_name')
    )
    op.create_index('idx_catalog_tags', 'context_catalog', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('context_entries',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Text(), server_default='team', nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Text(), server_default='medium', nullable=False),
    sa.Column('evidence_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(detail, '') || ' ' || content)", persisted=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_context_not_deleted', 'context_entries', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_context_tenant_file', 'context_entries', ['tenant_id', 'file_name'], unique=False)
    op.create_index('idx_context_visibility', 'context_entries', ['tenant_id', 'visibility'], unique=False)
    op.create_index('idx_context_search', 'context_entries', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Text(), server_default='anonymous', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now() + interval '7 days'"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('rendered_html', sa.Text(), nullable=True),
    sa.Column('attribution', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('events_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_pending', 'skill_runs', ['status', 'scheduled_for'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('uploaded_files',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tenants',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_index('idx_one_active_tenant', 'user_tenants', ['user_id'], unique=True, postgresql_where=sa.text('active = true'))
    op.create_table('work_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='upcoming', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_items_upcoming', 'work_items', ['tenant_id', 'scheduled_at'], unique=False, postgresql_where=sa.text("status = 'upcoming'"))
    op.create_table('context_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['context_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_tenant_time', 'context_events', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_tenant_time', table_name='context_events')
    op.drop_table('context_events')
    op.drop_index('idx_work_items_upcoming', table_name='work_items', postgresql_where=sa.text("status = 'upcoming'"))
    op.drop_table('work_items')
    op.drop_index('idx_one_active_tenant', table_name='user_tenants', postgresql_where=sa.text('active = true'))
    op.drop_table('user_tenants')
    op.drop_table('uploaded_files')
    op.drop_index('idx_runs_pending', table_name='skill_runs', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('skill_runs')
    op.drop_table('onboarding_sessions')
    op.drop_index('idx_context_search', table_name='context_entries', postgresql_using='gin')
    op.drop_index('idx_context_visibility', table_name='context_entries')
    op.drop_index('idx_context_tenant_file', table_name='context_entries')
    op.drop_index('idx_context_not_deleted', table_name='context_entries', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('context_entries')
    op.drop_index('idx_catalog_tags', table_name='context_catalog', postgresql_using='gin')
    op.drop_table('context_catalog')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index('idx_enrichment_cache_ttl', table_name='enrichment_cache')
    op.drop_table('enrichment_cache')
    # ### end Alembic commands ###
